"""
GET /api/documents?topic=X           — List indexed documents for a topic.
GET /api/suggested-questions?topic=X — Dynamically generated starter questions.

Suggested questions are generated by sampling 10 random chunks from the topic
collection and asking gpt-4o-mini to propose 4 natural questions a user might
ask.  Results are cached in memory for 1 hour per topic, or until invalidated
by a write operation.
"""

import json
import logging
import time

from fastapi import APIRouter, HTTPException, Query
from openai import OpenAI

from app.config import TOPICS, settings
from app.models import (
    DocumentListResponse,
    DocumentResponse,
    FollowUpQuestionsRequest,
    SuggestedQuestionsResponse,
)
from app.services.vector_store import get_all_documents, get_sample_chunks

router = APIRouter()
log = logging.getLogger(__name__)

# ── Suggested-question cache ─────────────────────────────────
# Keyed by topic ID.  Each entry holds (questions, expiry_timestamp).

_CACHE_TTL = 3600  # seconds

_sq_cache: dict[str, tuple[list[str], float]] = {}


def invalidate_question_cache(topic_id: str | None = None) -> None:
    """
    Drop one topic's cache entry (or all entries if topic_id is None).
    Call this whenever documents are added to or removed from a collection.
    """
    if topic_id:
        _sq_cache.pop(topic_id, None)
    else:
        _sq_cache.clear()


_FALLBACK_QUESTIONS = [
    "What topics are covered in these documents?",
    "Summarize the key points",
    "What are the most important policies?",
    "What procedures are described?",
]

_GENERATION_PROMPT = """\
Based on the following excerpts from a knowledge base, generate exactly 4 natural \
questions that a user would likely ask. The questions should:
- Cover different topics/sections from the excerpts
- Be specific enough to get useful answers
- Sound like a real person asking (not robotic)
- Be answerable from the knowledge base content

Return ONLY a JSON array of 4 strings, no other text.

Excerpts:
{chunks}"""


def _generate_questions(topic_id: str) -> list[str]:
    """
    Sample 10 chunks from the topic collection and ask the LLM to suggest
    4 questions.  Returns the fallback list if anything fails.
    """
    # Check cache first
    if topic_id in _sq_cache:
        questions, expires_at = _sq_cache[topic_id]
        if time.time() < expires_at:
            log.debug("suggested-questions cache hit for topic=%s", topic_id)
            return questions

    chunks = get_sample_chunks(topic_id, n=10)
    if not chunks:
        return _FALLBACK_QUESTIONS

    excerpt_block = "\n\n---\n\n".join(c[:400] for c in chunks)
    prompt = _GENERATION_PROMPT.format(chunks=excerpt_block)

    try:
        client = OpenAI(api_key=settings.OPENAI_API_KEY)
        response = client.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=256,
        )
        raw = (response.choices[0].message.content or "").strip()

        # Strip markdown code fences if the model wraps its output
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        questions: list[str] = json.loads(raw)
        if not isinstance(questions, list) or not questions:
            raise ValueError("Unexpected LLM response shape")
        # Ensure plain strings, keep at most 4
        questions = [str(q) for q in questions[:4]]

    except Exception as exc:
        log.warning("suggested-questions generation failed for topic=%s: %s", topic_id, exc)
        return _FALLBACK_QUESTIONS

    # Populate cache
    _sq_cache[topic_id] = (questions, time.time() + _CACHE_TTL)
    return questions


# ── Helpers ──────────────────────────────────────────────────

def _validate_topic(topic: str) -> None:
    if topic not in TOPICS:
        valid = ", ".join(TOPICS.keys())
        raise HTTPException(
            status_code=400,
            detail=f"Unknown topic '{topic}'. Valid topics: {valid}",
        )


# ── GET /api/documents ───────────────────────────────────────

@router.get("/documents", response_model=DocumentListResponse)
async def list_documents(topic: str = Query(..., description="Topic ID")):
    """Return all indexed documents for the specified topic."""
    _validate_topic(topic)
    docs_meta = get_all_documents(topic)
    documents = [
        DocumentResponse(
            doc_id=m["doc_id"],
            filename=m["filename"],
            file_type=m["file_type"],
            chunk_count=m["chunk_count"],
            word_count=m.get("word_count", 0),
            uploaded_at=m.get("uploaded_at", ""),
        )
        for m in docs_meta
    ]
    return DocumentListResponse(documents=documents, total_count=len(documents))


# ── GET /api/suggested-questions ────────────────────────────

@router.get("/suggested-questions", response_model=SuggestedQuestionsResponse)
async def suggested_questions(topic: str = Query(..., description="Topic ID")):
    """
    Return 4 contextual starter questions generated from the topic's content.

    Results are cached for 1 hour per topic.  If the collection is empty or
    the LLM call fails, returns a generic fallback list.
    """
    _validate_topic(topic)
    questions = _generate_questions(topic)
    return SuggestedQuestionsResponse(questions=questions)


# ── POST /api/suggested-questions/follow-up ──────────────────

_FOLLOW_UP_PROMPT = """\
Based on the following Q&A exchange and knowledge base excerpts, generate exactly 4 \
follow-up questions the user might want to ask next. Questions should:
- Naturally flow from the previous conversation
- Dig deeper into related topics available in the knowledge base
- Be specific and practical
- Sound like a real person asking

Previous question: {last_question}

Previous answer: {last_answer}

Knowledge base excerpts:
{chunks}

Return ONLY a JSON array of 4 strings, no other text."""


@router.post("/suggested-questions/follow-up", response_model=SuggestedQuestionsResponse)
async def follow_up_questions(request: FollowUpQuestionsRequest):
    """
    Generate 4 follow-up questions based on the last Q&A exchange and topic content.
    Not cached — each response is contextual to the specific conversation turn.
    """
    _validate_topic(request.topic)

    chunks = get_sample_chunks(request.topic, n=6)
    excerpt_block = "\n\n---\n\n".join(c[:400] for c in chunks) if chunks else "(no excerpts available)"

    prompt = _FOLLOW_UP_PROMPT.format(
        last_question=request.last_question.strip(),
        last_answer=request.last_answer.strip()[:1000],
        chunks=excerpt_block,
    )

    try:
        client = OpenAI(api_key=settings.OPENAI_API_KEY)
        response = client.chat.completions.create(
            model=settings.LLM_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=256,
        )
        raw = (response.choices[0].message.content or "").strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        questions: list[str] = json.loads(raw)
        if not isinstance(questions, list) or not questions:
            raise ValueError("Unexpected LLM response shape")
        questions = [str(q) for q in questions[:4]]

    except Exception as exc:
        log.warning("follow-up question generation failed for topic=%s: %s", request.topic, exc)
        questions = _FALLBACK_QUESTIONS

    return SuggestedQuestionsResponse(questions=questions)
